default: findCommitDiff extractCOmmitFromDisk

findCommitDiff: findCommitDiff.c
	gcc -o findCommitDiff findCommitDiff.c

extractCOmmitFromDisk: extractCommitFromDisk.c
	gcc -o extractCommitFromDisk extractCommitFromDisk.c
