/*
 * $Id: ExplorerFrame.java,v 1.2 2004/12/07 17:53:22 bdickie Exp $
 *
 * Repository Explorer and Repository Grapher
 * Copyright (C) 2004 Blake Dickie
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or 
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 * MA 02111-1307 USA
 *
 */

package ca.uvic.cs.gold.bdickie.explorer;

import ca.uvic.cs.gold.bdickie.ErrorLog;
import ca.uvic.cs.gold.bdickie.fs.*;
import javax.swing.tree.DefaultMutableTreeNode;

/** The main window of the Repository Browser, most functionality is handled
 *  in the other classes through.
 *
 * @author  Blake Dickie
 */
public class ExplorerFrame extends javax.swing.JFrame {
    FilesTabbedPane tabPane;
    
    /** Creates new form ExplorerFrame */
    public ExplorerFrame() {
        initComponents();
        tabPane = new FilesTabbedPane();
        rightPanel.add(tabPane);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        filesTree = new javax.swing.JTree();
        rightPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuOptions = new javax.swing.JMenuItem();
        mnuQuit = new javax.swing.JMenuItem();

        setTitle("Repository Browse");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        filesTree.setCellRenderer(new FileSystemRenderer());
        filesTree.setModel(TreeModelGenerator.getDirectoryModel());
        filesTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filesTreeMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(filesTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        rightPanel.setLayout(new java.awt.BorderLayout());

        rightPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        rightPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        jSplitPane1.setRightComponent(rightPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");
        mnuFile.setMnemonic('f');
        mnuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileActionPerformed(evt);
            }
        });

        mnuOptions.setText("Options");
        mnuOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOptionsActionPerformed(evt);
            }
        });

        mnuFile.add(mnuOptions);

        mnuQuit.setMnemonic('x');
        mnuQuit.setText("Exit");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });

        mnuFile.add(mnuQuit);

        jMenuBar1.add(mnuFile);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void mnuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuFileActionPerformed

    private void mnuOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOptionsActionPerformed
        ConfigurationDialog.show(this);
        filesTree.setModel(TreeModelGenerator.getDirectoryModel());
        FileExplorer.reset();
    }//GEN-LAST:event_mnuOptionsActionPerformed

    private void filesTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filesTreeMouseClicked
        if (evt.getClickCount() == 2)
        {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode)filesTree.getSelectionPath().getLastPathComponent();
            Object value = node.getUserObject();
            if (value instanceof File)
            {
                File f = (File)value;
                tabPane.openFile(f, true);
            }
        }
    }//GEN-LAST:event_filesTreeMouseClicked

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        ErrorLog.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        ErrorLog.exit(0);
    }//GEN-LAST:event_exitForm
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree filesTree;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuOptions;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
    
}

/* ChangeLog:
 *   $Log: ExplorerFrame.java,v $
 *   Revision 1.2  2004/12/07 17:53:22  bdickie
 *   Done Repository Grapher and added GPL boilerplate to older files.
 *
 *   Revision 1.1  2004/11/01 02:24:20  bdickie
 *   Done Repository Browser.
 *
 */
