#!/usr/bin/perl

use strict;


my %rotation = (
    "normal" =>    0,
    "right" =>     1,
    "inverted" =>  2,
    "left"  =>     3,
    );

my @rotationInv = (
    "normal",
    "right",
    "inverted",
    "left"
    );


my @wacom = (0, 1, 3, 2);


my $next = $ARGV[0];


my $current = Find_Display_Rotation();

if ($next eq "-") {
    $current --;
} elsif ($next eq "+" ) {
    $current ++;
} elsif ($next eq "") {
    $current ++;
} else {
    $current = $next;
}
$current %=4;
print "Setting to : $current\n";

die "invalid current [$current]" unless $current >= 0 and $current <4;

# set xrandr

print "Setting $rotationInv[$current]\n";
print `xrandr -display :0.0 -o $rotationInv[$current]`;
print `xsetwacom set stylus Rotate $wacom[$current]`;
exit;



sub Find_Display_Rotation
{
    my $mode = `/usr/bin/xrandr --verbose| grep LVDS`;

    if ($mode =~ / +([a-z]+) +\(/) {
    } else {
        print STDERR "UNable to detect mode $mode\n";
	die;
    }
    die "($mode) ($1) " if ($1 ne "right" and
			    $1 ne "left" and
			    $1 ne "inverted" and
			    $1 ne "normal");

    return $rotation{$1};
}
