/*
 * $Id: GraphFrame.java,v 1.1 2004/12/07 17:53:23 bdickie Exp $
 *
 * Repository Explorer and Repository Grapher
 * Copyright (C) 2004 Blake Dickie
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or 
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 * MA 02111-1307 USA
 *
 */
package ca.uvic.cs.gold.bdickie.graphview;

import ca.uvic.cs.gold.bdickie.fs.*;
import javax.swing.*;

import ca.uvic.cs.gold.bdickie.graphview.framework.*;

/** The primary Window for the Repository Grapher.
 *
 * @author  Blake Dickie
 */
public class GraphFrame extends javax.swing.JFrame {
    GraphsTabbedPane tabbedPane;
    
    /** Creates new form GraphFrame */
    public GraphFrame() {
        initComponents();
        tabbedPane = new GraphsTabbedPane(this);
        panMain.add(tabbedPane);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        panMain = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuNewGraph = new javax.swing.JMenuItem();
        mnuSettings = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnuQuit = new javax.swing.JMenuItem();

        setTitle("Repository Grapher");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panMain.setLayout(new java.awt.BorderLayout());

        panMain.setPreferredSize(new java.awt.Dimension(600, 400));
        panMain.setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().add(panMain, java.awt.BorderLayout.CENTER);

        mnuFile.setText("Graph");
        mnuNewGraph.setText("New Graph");
        mnuNewGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewGraphActionPerformed(evt);
            }
        });

        mnuFile.add(mnuNewGraph);

        mnuSettings.setText("Settings");
        mnuSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSettingsActionPerformed(evt);
            }
        });

        mnuFile.add(mnuSettings);

        mnuFile.add(jSeparator2);

        mnuQuit.setText("Exit");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });

        mnuFile.add(mnuQuit);

        jMenuBar2.add(mnuFile);

        setJMenuBar(jMenuBar2);

        pack();
    }//GEN-END:initComponents

    private void mnuSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSettingsActionPerformed
        ConfigurationDialog.show(this);
        JOptionPane.showMessageDialog(this,"Some settings may not take effect until you restart.");
    }//GEN-LAST:event_mnuSettingsActionPerformed

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        ca.uvic.cs.gold.bdickie.ErrorLog.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed

    private void mnuNewGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewGraphActionPerformed
        GraphSettings settings = NewGraphViewWizard.showWizard(this);
        LoadingDialog dialog = new LoadingDialog(this, true);
        new GraphInitThread(settings, dialog);
        dialog.show();
        
    }//GEN-LAST:event_mnuNewGraphActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        ca.uvic.cs.gold.bdickie.ErrorLog.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new GraphFrame().show();
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuNewGraph;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuSettings;
    private javax.swing.JPanel panMain;
    // End of variables declaration//GEN-END:variables
    
    /** To avoid locking up the GUI (Java uses one thread for all the 
     *  GUI related calls and event handling so any code ran from an
     *  event handler locks up the GUI), the graph initalization which can
     *  take a while is ran in a seperate thread.
     */
    private class GraphInitThread extends Thread
    {
        private GraphSettings settings;
        private LoadingDialog dialog;
        
        public GraphInitThread(GraphSettings settings, LoadingDialog dialog)
        {
            this.settings = settings;
            this.dialog = dialog;
            start();
        }
        
        public void run()
        {
            // Yield control back to the other thread to enture that the dialog
            // is opened.
            Thread.yield();
            Graph graph = new Graph(settings);
            dialog.hide();
            tabbedPane.open(graph);
        }
    }
}

/* ChangeLog:
 *   $Log: GraphFrame.java,v $
 *   Revision 1.1  2004/12/07 17:53:23  bdickie
 *   Done Repository Grapher and added GPL boilerplate to older files.
 *
 */
