/*
 * $Id: LayerDepthDialog.java,v 1.1 2004/12/07 17:53:23 bdickie Exp $
 *
 * Repository Explorer and Repository Grapher
 * Copyright (C) 2004 Blake Dickie
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or 
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 * MA 02111-1307 USA
 *
 */

package ca.uvic.cs.gold.bdickie.graphview;

/** A dialog for entering the radius of one layer of the graph.
 *  Could perhaps benifit from a slider in future modifications.
 *
 * @author  Blake Dickie
 */
public class LayerDepthDialog extends javax.swing.JDialog {
    private int initialValue;
    private int returnValue;
    
    /** Creates new form LayerDepthDialog */
    public LayerDepthDialog(java.awt.Frame parent, int initialValue) {
        super(parent, true);
        this.initialValue = initialValue;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        txtLayerDepth = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        butOk = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();

        setTitle("Layer Depth");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Enter the radius of one layer of the tree:");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        txtLayerDepth.setText(String.valueOf(initialValue));
        getContentPane().add(txtLayerDepth, java.awt.BorderLayout.CENTER);

        butOk.setText("Ok");
        butOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOkActionPerformed(evt);
            }
        });

        jPanel1.add(butOk);

        butCancel.setText("Cancel");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        jPanel1.add(butCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void butOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOkActionPerformed
        try {
            returnValue = Integer.parseInt(txtLayerDepth.getText());
            hide();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(txtLayerDepth, "Please enter an integer.");
        }
    }//GEN-LAST:event_butOkActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        returnValue = initialValue;
        hide();
    }//GEN-LAST:event_butCancelActionPerformed
    
    public static int getLayerDepth(java.awt.Frame parent, int initialDepth)
    {
        LayerDepthDialog dialog = new LayerDepthDialog(parent, initialDepth);
        dialog.show();
        return dialog.returnValue;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLayerDepth;
    // End of variables declaration//GEN-END:variables
    
}

/* ChangeLog:
 *   $Log: LayerDepthDialog.java,v $
 *   Revision 1.1  2004/12/07 17:53:23  bdickie
 *   Done Repository Grapher and added GPL boilerplate to older files.
 *
 */
