#!/bin/bash
INTERFACE=$1
STATUS=$2
NETWORK=`iwconfig wlan0 | head -1 | perl -pe 's/^.*ESSID:"([^"]+)".*$/$1/'`

echo "Start dispatcher "  >> /tmp/nm.txt
echo "INTERFACE [$INTERFACE] Status [$STATUS] network [$NETWORK]" >> /tmp/nm.txt



wait_for_process() {
  PNAME=$1
  PID=`/usr/bin/pgrep $PNAME`
  while [ -z "$PID" ]; do
        sleep 3;
        PID=`/usr/bin/pgrep $PNAME`
  done
}



if [ "$INTERFACE" = "wlan0" ] && [ "$STATUS" = "up" ]; then
   if [ "$NETWORK" = "forCustomersOnlyAskForPassword" ]; then
      cp -p /etc/NetworkManager/data/hosts.saveBandwidth /etc/hosts
   fi
   echo "Status wlan0 up [$NETWORK]" >> /tmp/nm.txt
fi

if [ "$INTERFACE" = "wlan0" ] && [ "$STATUS" = "down" ]; then
    # restore hosts
   cp -p /etc/NetworkManager/data/hosts /etc/hosts
   echo "Status wlan0 down" >> /tmp/nm.txt
fi

echo `date` >> /tmp/nm.txt
echo "done" >> /tmp/nm.txt
