default:
	pdftoppm -r 75	on2011.pdf | pnmtopng > on2011.png
	pdftoppm -r 75	bc2011.pdf | pnmtopng > bc2011.png
	pdftoppm -r 75	ab2011.pdf | pnmtopng > ab2011.png
	pdftoppm -r 75	qc2011.pdf | pnmtopng > qc2011.png
	pdftoppm -r 75	nserc2011byInd.pdf | pnmtopng > nserc2011byInd.png
	pdftoppm -r 75	nserc2011byInd.pdf | pnmtopng > nserc2011byInd.png
	pdftoppm -r 75 nserc2011byInst.pdf | pnmtopng > nserc2011byInst.png
	pdftoppm -r 75 nserc2011byInstLabels.pdf | pnmtopng > nserc2011byInstLabels.png


#	./plots.R
