#!/usr/bin/perl

use strict;
use File::Basename;
use Getopt::Long;
use Pod::Usage;

my $verbose = 1;
my $debug   = 0;
my $noAttic = 0;
my $extractRevisions = 1;

my $dirPrefix = ""; # just in case this we want to remove a prefix to
		    # the filenames

my $tagsFileName = "cvs.tags";
my $man = 0;
my $help = 0;

GetOptions("verbose"		  => \$verbose,
	   "debug"		  => \$debug,
	   "dirprefix=s"	  => \$dirPrefix,
	   "help"                 => \$help,
	   "noAttic"		  => \$noAttic,
	   "man"                  => \$man,
	   "tagsFileName=s"       => \$tagsFileName,
	   ) or pod2usage(2);

pod2usage(1) if $help;
pod2usage(-verbose => 2) if $man;

pod2usage(1) if scalar(@ARGV) ==0 ;

$/ = "=============================================================================\n\nRCS file: ";



# if revisions... prepare file

my $totalBytes = 0;
my $readBytes = 0;


if ($verbose) {
    # Estimate number of bytes to process. This will give us an idea of how
    # much we have to do
    $totalBytes = Estimate_Total_Size(@ARGV);
}


open(TAGS, ">$tagsFileName") or
	die "Unable to create TAGs filename $tagsFileName $!\n";


while (my $fileName = shift) {
    Process_Log_File($fileName);
}


close TAGS;

exit 0;

# ----------------------------------------------------------------------


sub Process_Log_File
{
    my ($fileName) = @_;
    my ($countFiles, $revisions);

    open (IN, $fileName) || die "Unable to open input file $fileName\n";


    while (<IN>) {

	if ($verbose && $countFiles % 10 == 0) {
	    Display_Progress();
	}

	my $inAttic = 0;

	chomp;

	my $record =$_;

	die "Illegal file record $_,v\n" unless /^([^\n]+),v\nWorking file: ([^\n]+)\n/m;
	my $fileName = $2;
	my $rcsFile = $1;

# We really don't want to look at the attic, do we?
# ok, give the user the choice. and mark it in the output

	if (m@Attic@) {
	    next if $noAttic;
	    $inAttic = 1;
	}

# extract some other data

	my %tags = Extract_Tags($record);

	print TAGS  scalar (%tags) . "\n";

	print STDERR "$fileName; " . (scalar(%tags))/2 . "\n" if $debug;


    }
    Update_Progress();
    print STDERR "Processed $countFiles files in $fileName\n" if $verbose;
    close IN;

    return ($countFiles, $revisions);
}


sub Extract_Tags
{
    my ($record) =@_;
    my %tags  = ();

    if ($record =~ /symbolic names:\n((\t.+\n)+)/m) {
	my $sym = $1;
	split('\n', $sym);
	
    } else {
    }

    return %tags;
}


sub Estimate_Total_Size
{
    my @fileList = @_;
    my $total = 0;

    foreach my $fileName (@fileList) {

	my ( $dev, $ino, $mode, $nlink,
	     $uid, $gid, $rdev, $size,
	     $atime, $mtime, $ctime,
	     $blksize, $blocks ) = stat($fileName)
	or die "file $fileName cannot be open: $!";
	$total += $size;
    }
    return $total;
}


sub Update_Progress
{
    $readBytes += tell(IN);
}


sub Display_Progress
{
    my $thisFileBytes = tell(IN);
    my $currentBytes = $readBytes + $thisFileBytes;

    printf("Progress: %5.2f\n" , ($currentBytes * 100.0) / ($totalBytes * 1.0));
}


__END__

=head1 NAME

sample - Using GetOpt::Long and Pod::Usage

=head1 SYNOPSIS

$0 [options] cvsLogFile...

 Options:
   --help                 Brief help message
   --man                  Full documentation
   --verbose              Display some useful progress messages
   --noAttic              Do not show records in the attic
   --dirprefix=s          Remove the given prefix from the front of each filename
   --revisionsFileName=s  Output filename for revisions

 cvsLogFile               File generated by cvs log

=head1 OPTIONS

=over 8

=item B<--help>

Print a brief help message and exits.

=item B<--man>

Prints the manual page and exits.

=item B<--verbose>

Show messages showing progress

=item B<--noAttic>

Ignore the files in the attic. For each directory, CVS maintains an
area (called the attic) where it moves files as they are "deleted"
from the module. By default, the attic is processed.

=item B<--dirprefix=dirname>

This option will allow you to remove a prefix from full filename.

=item B<--revisionsFileName=filename>

Name of the file with the revisions. Default cvs.revisions. Run $0
--man for an description of the format of this file.

=item B<--filesFileName=filename>

Name of the file with the files. Default cvs.files. Run $0
--man for an description of the format of this file.


=back

=head1 DESCRIPTION

  B<This program> will take as an input a file generated by running CVS
  log in a module. It creates two filenames as output:

  revisions.txt which contains each of the revisions for each of the
  files. The format of the output is:

  file                  -- full file name (matches filenames.txt)
  revisionId            -- id of the revision
  date                  -- date when it hapend
  author                -- userid of who made the change
  state                 -- I don't really know what this is
  linesAdded            -- number of lines added
  linesDeleted          -- number of lines deleted
  rev                   -- log message given to cvs commit

  the filenames.txt file contains the files in the log:

  filename,             -- the full file name (matches revisions.txt)
  basename,             -- only filename, without path or extension
  extension             -- extension
  directory             -- directory where the file is
  latest version        -- latest cvs version
  branch version        -- branch, if it exists
  totalrevisions        -- total number of revisions
  selected revisions    -- I don't really know what this is
  inAttic (0 or 1)      -- 0/1 whether the  file is in the attic
  rcsfilename           -- full path name of the RCS file
			   (no ,v at the end)


  Files are ; delimited, one record per line. The character \b is
  replaced with NEWLINE and ; is replaced with SEMICOLON


=cut
