default:
	pdftoppm -r 100	on2013.pdf | pnmtopng > on2013.png
	pdftoppm -r 100	bc2013.pdf | pnmtopng > bc2013.png
	pdftoppm -r 100	ab2013.pdf | pnmtopng > ab2013.png
	pdftoppm -r 100	qc2013.pdf | pnmtopng > qc2013.png
	pdftoppm -r 100	nserc2013byInd.pdf | pnmtopng > nserc2013byInd.png
	pdftoppm -r 100	nserc2013byInd.pdf | pnmtopng > nserc2013byInd.png
	pdftoppm -r 100 nserc2013byInst.pdf | pnmtopng > nserc2013byInst.png
	pdftoppm -r 100 nserc2013byInstLabels.pdf | pnmtopng > nserc2013byInstLabels.png
	pdftoppm -r 100 nserc2013all.pdf | pnmtopng > nserc2013all.png


#	./plots.R
