default:
	pdftoppm -r 75	on2012.pdf | pnmtopng > on2012.png
	pdftoppm -r 75	bc2012.pdf | pnmtopng > bc2012.png
	pdftoppm -r 75	ab2012.pdf | pnmtopng > ab2012.png
	pdftoppm -r 75	qc2012.pdf | pnmtopng > qc2012.png
	pdftoppm -r 75	nserc2012byInd.pdf | pnmtopng > nserc2012byInd.png
	pdftoppm -r 75	nserc2012byInd.pdf | pnmtopng > nserc2012byInd.png
	pdftoppm -r 75 nserc2012byInst.pdf | pnmtopng > nserc2012byInst.png
	pdftoppm -r 75 nserc2012byInstLabels.pdf | pnmtopng > nserc2012byInstLabels.png


#	./plots.R
